export const iManagement = [
  {
    id: 1,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: 2,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: 3,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: 4,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
];
