export const iManagement = [
  {
    id: '1',
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: '2',
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: '3',
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: '4',
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
];
export const payElementData = [
  {
    id: '1',
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
  {
    id: '2',
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
  {
    id: '3',
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
  {
    id: '4',
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
];
export const payScaleData = [
  {
    id: '1',
    name: 'Test Scale',
    payElement: 'Test Element, test 2',
    payFrequency: 'Monthly',
    noOfEmployees: '34',
  },
  {
    id: '2',
    name: 'Test Scale',
    payElement: 'Test Element, test 2',
    payFrequency: 'Monthly',
    noOfEmployees: '34',
  },
  {
    id: '3',
    name: 'Test Scale',
    payElement: 'Test Element, test 2',
    payFrequency: 'Monthly',
    noOfEmployees: '34',
  },
  {
    id: '4',
    name: 'Test Scale',
    payElement: 'Test Element, test 2',
    payFrequency: 'Monthly',
    noOfEmployees: '34',
  },
];
export const employeeData = [
  {
    id: '1',
    name: 'John Doe',
    empId: '2345',
    department: 'Products',
    dateCreated: '23rd Nov 1999',
  },
  {
    id: '2',
    name: 'Jane Doe',
    empId: '2346',
    department: 'Products',
    dateCreated: '23rd Nov 1999',
  },
  {
    id: '3',
    name: 'Smith Davidson',
    empId: '2347',
    department: 'Research',
    dateCreated: '23rd Nov 1999',
  },
  {
    id: '4',
    name: 'Andrew Wams',
    empId: '2348',
    department: 'Development',
    dateCreated: '23rd Nov 1999',
  },
];
export const payscalePayrollData = [
  {
    id: '1',
    name: 'Tolu Aina',
    empId: '2345',
    totalEarning: '₦250,000',
    totalDeduction: '₦250,000',
    netPay: '₦250,000',
    hoursWorked: '8',
  },
  {
    id: '2',
    name: 'John Doe',
    empId: '2345',
    totalEarning: '₦250,000',
    totalDeduction: '₦250,000',
    netPay: '₦250,000',
    hoursWorked: '8',
  },
  {
    id: '3',
    name: 'Jane Doe',
    empId: '2345',
    totalEarning: '₦250,000',
    totalDeduction: '₦250,000',
    netPay: '₦250,000',
    hoursWorked: '8',
  },
  {
    id: '4',
    name: 'Andrew Wams',
    empId: '2345',
    totalEarning: '₦250,000',
    totalDeduction: '₦250,000',
    netPay: '₦250,000',
    hoursWorked: '8',
  },
];
export const grossPayrollData = [
  {
    id: '1',
    name: 'Tolu Aina',
    grossMothlySalary: '₦95,768.34',
    earnings: '₦95,768.34',
    deductions: '₦95,768.34',
    netSalary: '₦95,768.34',
    prorateDeduction: '0',
  },
  {
    id: '2',
    name: 'John Doe',
    grossMothlySalary: '₦95,768.34',
    earnings: '₦95,768.34',
    deductions: '₦95,768.34',
    netSalary: '₦95,768.34',
    prorateDeduction: '0',
  },
  {
    id: '3',
    name: 'Jane Doe',
    grossMothlySalary: '₦95,768.34',
    earnings: '₦95,768.34',
    deductions: '₦95,768.34',
    netSalary: '₦95,768.34',
    prorateDeduction: '0',
  },
  {
    id: '4',
    name: 'Andrew Wams',
    grossMothlySalary: '₦95,768.34',
    earnings: '₦95,768.34',
    deductions: '₦95,768.34',
    netSalary: '₦95,768.34',
    prorateDeduction: '0',
  },
];

export const payrollRunLog = [
  {
    id: '1',
    name: 'Test Pay',
    refNo: '#0282091-IG',
    period: '1st Dec - 25th Dec',
    dateApproved: '25th Dec',
    approvedBy: 'Tolu Allen',
    status: 'Approved',
  },
  {
    id: '2',
    name: 'Test Pay',
    refNo: '#0282091-IG',
    period: '1st Dec - 25th Dec',
    dateApproved: '25th Dec',
    approvedBy: 'Tolu Allen',
    status: 'Pending',
  },
  {
    id: '3',
    name: 'Test Pay',
    refNo: '#0282091-IG',
    period: '1st Dec - 25th Dec',
    dateApproved: '25th Dec',
    approvedBy: 'Tolu Allen',
    status: 'Pending',
  },
  {
    id: '4',
    name: 'Test Pay',
    refNo: '#0282091-IG',
    period: '1st Dec - 25th Dec',
    dateApproved: '25th Dec',
    approvedBy: 'Tolu Allen',
    status: 'Approved',
  },
];
