export const iManagement = [
  {
    id: 1,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: 2,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: 3,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
  {
    id: 4,
    name: 'Pencom',
    category: 'Pension',
    accountName: '*******',
    accountNumber: '123456789',
    bank: 'GTB',
    createdDate: '23rd Nov 1999',
  },
];
export const payElementData = [
  {
    id: 1,
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
  {
    id: 2,
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
  {
    id: 3,
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
  {
    id: 4,
    name: 'Test',
    payType: 'Monthly Pay',
    elementName: 'Test Element',
    elementCategory: 'Content',
    elementType: 'Content',
    amount: '₦250,000',
    institution: 'Pencom',
  },
];
